### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [Norconex/commons-wicket#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by essiembre** [comment]
It always had a license.  It is using Apache License 2.0 and that file is bundled at the root of the project directory, [here](https://github.com/Norconex/commons-wicket/blob/master/norconex-commons-wicket/LICENSE.txt).  I just made it clearer in the repo README.

**Comment by karan** [comment]
Awesome. Thanks @essiembre
