### ISSUE TITLE
Does this make good looking modals on Android?

### ISSUE THREAD

**Issue by chrisco484** [Norconex/commons-wicket#2]
We are using Wicket 6 with bootstrap modal forms but are having an issue with bootstrap modals extending past the boundaries on the screen on Android phones only.

On iPhones the modal forms stay within the bounds of the screen and so are acceptable.

I was wondering if you BootstrapModal and associated classes work better with all modal devices.

**Comment by essiembre** [comment]
I am not sure how much depends on how you use them, but modal dialogs with forms look good on Android in my own tests.

**Comment by chrisco484** [comment]
Actually we managed to get the standard wicket modals working ok on Android.

This SO helped - we set up a media query in the CSS so that it only affects small devices:

[https://stackoverflow.com/questions/18432394/how-to-make-twitter-bootstrap-modal-full-screen](https://stackoverflow.com/questions/18432394/how-to-make-twitter-bootstrap-modal-full-screen)

**Comment by essiembre** [comment]
Glad you found a solution.
